### ISSUE TITLE
Clean Repository and Other Conventions.

### ISSUE THREAD

**Issue by ayushagarwal95** [TanishaChawla/OS-Project#1]
@TanishaChawla Clean the repository by removing all files that are not supposed to be pushed, like the node_modules directory when working with Node.js projects, bower_components directory when working with bower. You could refer to Vinay's repository for a C# project. Also, make a habit of adding a proper README.md, .gitignore and LICENSE while creating a new repository.

**Comment by TanishaChawla** [comment]
@ayushagarwal95 Okay
